theme: jekyll-theme-cayman

title: Alumni Matematica Verona
description: L`associazione

logo: logo.png

plugins:
  - jekyll-multiple-languages-plugin

languages: ["it", "en"]
exclude_from_localizations: ["css"]
defaultLang: en
languageNames:
  it: Italiano
  en: English

# Google Analytics
google_analytics: UA-153291505-1

github:
  is_project_page: false
